apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zo0k2vb8d-dotnet-basic
  janus-idp.io/tekton: zo0k2vb8d-dotnet-basic
  backstage.io/kubernetes-id: zo0k2vb8d-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zo0k2vb8d-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
